PetsAlone.Mvc/Models/ErrorViewModel.cs
namespace PetsAlone.Mvc.Models
{
    public class ErrorViewModel
    {
        public string Error { get; set; }
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PetsAlone.Mvc/Controllers/PetsController.cs
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PetsAlone.Core;
using PetsAlone.Mvc.Constant;
using PetsAlone.Mvc.Models;

namespace PetsAlone.Mvc.Controllers
{
    public class PetsController : Controller
    {
        private readonly PetsDbContext _petsDbContext;
        public PetsController(PetsDbContext petsDbContext)
        {
            _petsDbContext = petsDbContext;
        }

        public IActionResult Index(int? petType)
        {
            var service = new PetsService();
            var result = service.GetAll(_petsDbContext);

            if (petType.HasValue)
            {
                result = result.Where(p => (int)p.PetType == petType.Value).ToList();
            }

            result = result.OrderByDescending(p => p.MissingSince).ToList();

            ViewBag.PetTypes = Enum.GetValues(typeof(PetType))
                                   .Cast<PetType>()
                                   .Select(e => new SelectListItem
                                   {
                                       Value = ((int)e).ToString(),
                                       Text = e.ToString()
                                   })
                                   .ToList();

            ViewBag.SelectedPetType = petType?.ToString();

            return View(result);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        public IActionResult Create()
        {
            ViewBag.PetTypes = Enum.GetValues(typeof(PetType))
                .Cast<PetType>()
                .Select(e => new SelectListItem { Value = ((int)e).ToString(), Text = e.ToString() })
                .ToList();

            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(My_Pet_Class pet)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.PetTypes = Enum.GetValues(typeof(PetType))
                    .Cast<PetType>()
                    .Select(e => new SelectListItem { Value = ((int)e).ToString(), Text = e.ToString() })
                    .ToList();

                return View(pet);
            }

            _petsDbContext.Pets.Add(pet);
            _petsDbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

PetsAlone.Mvc/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PetsAlone.Core;
using PetsAlone.Mvc.Models;

namespace PetsAlone.Mvc.Controllers
{
    /// <summary>
    /// This implementation is acceptable for the time being, let's focus on the
    /// other features that will help us get something live ASAP
    /// </summary>
     
    public class UsersController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;
       
        public UsersController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
      
        public IActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Login(string username, string password, string returnUrl)
        {
            var loginResult = await _signInManager.PasswordSignInAsync(username, password, isPersistent: false, lockoutOnFailure: false);

            if (!loginResult.Succeeded)
            {
                return View(new ErrorViewModel {Error = "Invalid Username or Password"});
            }

            var user = await _userManager.FindByNameAsync(username);
            
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Sid, user.Id),
                new Claim(ClaimTypes.Name, user.UserName)
            };
            
            var claimsIdentity = new ClaimsIdentity(claims, "Login");
 
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
            
            return Redirect(returnUrl ?? "/");
        }
    }
}

PetsAlone.Mvc/Views/Pets/Create.cshtml
@model PetsAlone.Core.My_Pet_Class

@{
    ViewData["Title"] = "Create";
}

<h2 class="my-4">Report Missing Pet</h2>

<form asp-action="Create" method="post" class="mb-4">
    @Html.AntiForgeryToken()
    <div class="row mb-3">
        <div class="col-md-6">
            <label asp-for="Name" class="form-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-6">
            <label asp-for="PetType" class="form-label"></label>
            <select asp-for="PetType" asp-items="@(ViewBag.PetTypes as List<SelectListItem>)" class="form-select"></select>
            <span asp-validation-for="PetType" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-md-6">
            <label asp-for="MissingSince" class="form-label"></label>
            <input asp-for="MissingSince" type="date" class="form-control" />
            <span asp-validation-for="MissingSince" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a asp-action="Index" class="btn btn-secondary ms-2">Back to List</a>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PetsAlone.Mvc/Views/Pets/Index.cshtml
@model List<PetsAlone.Core.My_Pet_Class>

@{
    ViewData["Title"] = "Home Page";
}

@if (User.Identity.IsAuthenticated)
{
    <div class="text-center">
        <h1 class="display-4">Hello, @User.Identity.Name!</h1>
    </div>
}
<h2 class="my-4">Missing Pets</h2>

<form method="get" class="mb-4">
    <div class="row justify-content-start align-items-center">
        <div class="col-md-3">
            <label for="petType" class="form-label">Filter by Pet Type:</label>
            <select name="petType" id="petType" class="form-select" onchange="this.form.submit()">
                <option value="">All</option>
                @foreach (var type in (List<SelectListItem>)ViewBag.PetTypes)
                {
                    @if (ViewBag.SelectedPetType == type.Value)
                    {
                        <option value="@type.Value" selected="selected">@type.Text</option>
                    }
                    else
                    {
                        <option value="@type.Value">@type.Text</option>
                    }
                }
            </select>
        </div>
    </div>
</form>

<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Missing Since</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pet in Model)
        {
            <tr>
                <td>@pet.Name</td>
                <td>
                    @foreach (var petType in (List<SelectListItem>)ViewBag.PetTypes)
                    {
                        @if (petType.Value == pet.PetType.ToString())
                        {
                            @petType.Text
                        }
                    }
                </td>
                <td>@pet.MissingSince.ToShortDateString()</td>
            </tr>
        }
    </tbody>
</table>

@if (User.Identity.IsAuthenticated)
{
    <div class="my-4">
        <a class="btn btn-primary" asp-controller="Pets" asp-action="Create">Report Missing Pet</a>
    </div>
}

PetsAlone.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PetsAlone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Pets" asp-action="Index">PetsAlone MVC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - PetsAlone.Mvc - <a asp-area="" asp-controller="Pets" asp-action="Index">Home</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PetsAlone.Mvc/Views/Users/Login.cshtml
@model PetsAlone.Mvc.Models.ErrorViewModel
<form method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div>
        @if (Model != null)
        {
            <label style="color: red">@Model.Error</label>
        }
    </div>
    <button class="btn btn-primary">Sign in</button>
</form>